package okl.jspacjent.model;
// Generated 2006-12-05 16:02:43 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import okl.jspacjent.services.loginservice.IAccount;

/**
 * Lekarz generated by hbm2java
 */
public class Lekarz implements java.io.Serializable, IAccount {

  // Fields  
  private static final long serialVersionUID = 1L;
  // in database	
  private long   idLekarz;
  private String imie;
  private String nazwisko = "?";
  private String uwagi;
  
  private Set    przyjecies = new HashSet(0);

  // to login service
  private boolean loggedIn;
  private boolean revoked;
  
  // Constructors

  /** default constructor */
  public Lekarz() {
  }

  /** minimal constructor */
  public Lekarz(long idLekarz, String nazwisko) {
    this.idLekarz = idLekarz;
    this.nazwisko = nazwisko;
  }
  /** full constructor */
  public Lekarz(long idLekarz, String imie, String nazwisko,
      String uwagi, Set przyjecies) {
    this.idLekarz = idLekarz;
    this.imie = imie;
    this.nazwisko = nazwisko;
    this.uwagi = uwagi;
    this.przyjecies = przyjecies;
  }

  // Property accessors
  public long getIdLekarz() {
    return this.idLekarz;
  }

  public void setIdLekarz(long idLekarz) {
    this.idLekarz = idLekarz;
  }
  public String getImie() {
    return this.imie;
  }

  public void setImie(String imie) {
    this.imie = imie;
  }
  public String getNazwisko() {
    return this.nazwisko;
  }

  public void setNazwisko(String nazwisko) {
    this.nazwisko = nazwisko;
  }
  public String getUwagi() {
    return this.uwagi;
  }

  public void setUwagi(String uwagi) {
    this.uwagi = uwagi;
  }
  public Set getPrzyjecies() {
    return this.przyjecies;
  }

  public void setPrzyjecies(Set przyjecies) {
    this.przyjecies = przyjecies;
  }
  
  /** */
  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if ( !( other instanceof Lekarz ) )
      return false;        
    Lekarz castOther = (Lekarz) other;
    // Wystarczy porównaæ identyfikator
    return ( ( this.getIdLekarz() == castOther.getIdLekarz() ) );
  }
  
  /** */
  public String toString() {
    String tmp = "";
    //tmp += (new Long(this.getIdLekarz())).toString() + " , " ;
    tmp += this.getNazwisko() + " " ;    
    tmp += this.getImie()     + "   " ;    
    tmp += this.getUwagi()    + "" ;
    return tmp; 
  }

	@Override
	public void setLoggedIn(boolean value) {		
		this.loggedIn = value;
	}
	
	@Override
	public boolean isLoggedIn() {		
		return this.loggedIn;
	}
	
	@Override
	public void setRevoked(boolean value) {		
		this.revoked = value;
	}
	
	@Override
	public boolean isRevoked() {		
		return this.revoked;
	}
	
		
	@Override
	public String getId() {
		// nazwisko jest identyfikatorem wg. IAccount
		return this.getNazwisko();
	}
	
	@Override
	public boolean passwordMatches(String candidate) {
		// TODO Auto-generated method stub
		return false;
	}

}
